// Code generated by 'yaegi extract github.com/LightningDev1/dgc'. DO NOT EDIT.

package dgc

import (
	"github.com/LightningDev1/dgc"
	"reflect"
)

var Symbols = map[string]map[string]reflect.Value{}

func init() {
	Symbols["github.com/LightningDev1/dgc/dgc"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CodeblockLanguages":  reflect.ValueOf(&dgc.CodeblockLanguages).Elem(),
		"Create":              reflect.ValueOf(dgc.Create),
		"NewRateLimiter":      reflect.ValueOf(dgc.NewRateLimiter),
		"ParseArguments":      reflect.ValueOf(dgc.ParseArguments),
		"RegexArguments":      reflect.ValueOf(&dgc.RegexArguments).Elem(),
		"RegexBigCodeblock":   reflect.ValueOf(&dgc.RegexBigCodeblock).Elem(),
		"RegexChannelMention": reflect.ValueOf(&dgc.RegexChannelMention).Elem(),
		"RegexRoleMention":    reflect.ValueOf(&dgc.RegexRoleMention).Elem(),
		"RegexSmallCodeblock": reflect.ValueOf(&dgc.RegexSmallCodeblock).Elem(),
		"RegexUserMention":    reflect.ValueOf(&dgc.RegexUserMention).Elem(),

		// type definitions
		"Argument":           reflect.ValueOf((*dgc.Argument)(nil)),
		"Arguments":          reflect.ValueOf((*dgc.Arguments)(nil)),
		"Category":           reflect.ValueOf((*dgc.Category)(nil)),
		"Codeblock":          reflect.ValueOf((*dgc.Codeblock)(nil)),
		"Command":            reflect.ValueOf((*dgc.Command)(nil)),
		"Ctx":                reflect.ValueOf((*dgc.Ctx)(nil)),
		"DefaultRateLimiter": reflect.ValueOf((*dgc.DefaultRateLimiter)(nil)),
		"ExecutionHandler":   reflect.ValueOf((*dgc.ExecutionHandler)(nil)),
		"HelpMessage":        reflect.ValueOf((*dgc.HelpMessage)(nil)),
		"Middleware":         reflect.ValueOf((*dgc.Middleware)(nil)),
		"ObjectsMap":         reflect.ValueOf((*dgc.ObjectsMap)(nil)),
		"RateLimiter":        reflect.ValueOf((*dgc.RateLimiter)(nil)),
		"Router":             reflect.ValueOf((*dgc.Router)(nil)),

		// interface wrapper definitions
		"_RateLimiter": reflect.ValueOf((*_github_com_LightningDev1_dgc_RateLimiter)(nil)),
	}
}

// _github_com_LightningDev1_dgc_RateLimiter is an interface wrapper for RateLimiter type
type _github_com_LightningDev1_dgc_RateLimiter struct {
	IValue           interface{}
	WNotifyExecution func(a0 *dgc.Ctx) bool
}

func (W _github_com_LightningDev1_dgc_RateLimiter) NotifyExecution(a0 *dgc.Ctx) bool {
	return W.WNotifyExecution(a0)
}
